server:
  tomcat:
    threads:
      max: ${TOMCAT_MAX_THREADS:200}                # 생성할 수 있는 thread의 총 개수
      min-spare: ${TOMCAT_MIN_SPARE:10}           # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: ${TOMCAT_MAX_CONNECTIONS:8192}     # 수립가능한 connection의 총 개수
    accept-count: ${TOMCAT_ACCEPT_COUNT:100}         # 작업큐의 사이즈
    connection-timeout: ${TOMCAT_CONNECTION_TIMEOUT:20000} # timeout 판단 기준 시간, 20초
  port: ${TOMCAT_PORT:8080}                  # 서버를 띄울 포트번호
